package com.briup.jz.bean;

import java.io.Serializable;

public class RolePrivilege implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role_privilege.id
     *
     * @mbg.generated Wed Dec 02 20:04:38 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role_privilege.role_id
     *
     * @mbg.generated Wed Dec 02 20:04:38 CST 2020
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role_privilege.priviege_id
     *
     * @mbg.generated Wed Dec 02 20:04:38 CST 2020
     */
    private Long priviegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_role_privilege
     *
     * @mbg.generated Wed Dec 02 20:04:38 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role_privilege.id
     *
     * @return the value of base_role_privilege.id
     *
     * @mbg.generated Wed Dec 02 20:04:38 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role_privilege.id
     *
     * @param id the value for base_role_privilege.id
     *
     * @mbg.generated Wed Dec 02 20:04:38 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role_privilege.role_id
     *
     * @return the value of base_role_privilege.role_id
     *
     * @mbg.generated Wed Dec 02 20:04:38 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role_privilege.role_id
     *
     * @param roleId the value for base_role_privilege.role_id
     *
     * @mbg.generated Wed Dec 02 20:04:38 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role_privilege.priviege_id
     *
     * @return the value of base_role_privilege.priviege_id
     *
     * @mbg.generated Wed Dec 02 20:04:38 CST 2020
     */
    public Long getPriviegeId() {
        return priviegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role_privilege.priviege_id
     *
     * @param priviegeId the value for base_role_privilege.priviege_id
     *
     * @mbg.generated Wed Dec 02 20:04:38 CST 2020
     */
    public void setPriviegeId(Long priviegeId) {
        this.priviegeId = priviegeId;
    }
}